@startwbs
* Organisatie:\nLectoraat Energietransititie
** Product Owner:\nNick van Ravenzwaai
** Opdrachtgever:\nHenri ter Hofte
*** Developer:\n Jesse Brand
*** Developer:\n Rick Klaasboer
*** Developer:\n Joël Kuijper
*** Developer:\n Ward Pieters
@endwbs
